name: therepublicofchocolate
favicon: null
layout_spectrum: 0.28751942445524037
typography_spectrum: 0.8088539782911539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25376428524032235
  lightness: 0.06620416836813092
  saturation: 0.6086416232865304
  rhythmicContrast: 0.4654547676909715
purpose: []
